/**
 * Íconos de línea Lucide, del color del texto. Nunca emojis.
 * Mapa explícito para que el bundle incluya solo los íconos usados.
 */
import {
  BadgeCheck,
  Bug,
  Calculator,
  Camera,
  ChartColumn,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  ClipboardList,
  Clock,
  CloudAlert,
  CloudCheck,
  CloudOff,
  CloudUpload,
  Delete,
  Download,
  Eye,
  EyeOff,
  Flag,
  HardHat,
  House,
  Image,
  ImagePlus,
  Info,
  ListChecks,
  LockKeyhole,
  LogOut,
  Map,
  MapPin,
  Mic,
  Minus,
  Package,
  Play,
  Plus,
  RefreshCw,
  Route,
  Satellite,
  ScanQrCode,
  ScanSearch,
  Settings,
  ShieldCheck,
  Siren,
  Smartphone,
  SprayCan,
  Square,
  SquarePlus,
  Table,
  Tractor,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  UserRound,
  Users,
  Wifi,
  X,
  type LucideIcon,
} from 'lucide-react-native';
import { campo, semantico } from './tema';

const ICONOS: Record<string, LucideIcon> = {
  'badge-check': BadgeCheck,
  bug: Bug,
  calculator: Calculator,
  camera: Camera,
  'chart-column': ChartColumn,
  check: Check,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'clipboard-list': ClipboardList,
  clock: Clock,
  'cloud-alert': CloudAlert,
  'cloud-check': CloudCheck,
  'cloud-off': CloudOff,
  'cloud-upload': CloudUpload,
  delete: Delete,
  download: Download,
  eye: Eye,
  'eye-off': EyeOff,
  flag: Flag,
  'hard-hat': HardHat,
  house: House,
  image: Image,
  'image-plus': ImagePlus,
  info: Info,
  'list-checks': ListChecks,
  'lock-keyhole': LockKeyhole,
  'log-out': LogOut,
  map: Map,
  'map-pin': MapPin,
  mic: Mic,
  minus: Minus,
  package: Package,
  play: Play,
  plus: Plus,
  'refresh-cw': RefreshCw,
  route: Route,
  satellite: Satellite,
  'scan-qr-code': ScanQrCode,
  'scan-search': ScanSearch,
  settings: Settings,
  'shield-check': ShieldCheck,
  siren: Siren,
  smartphone: Smartphone,
  'spray-can': SprayCan,
  square: Square,
  'square-plus': SquarePlus,
  table: Table,
  tractor: Tractor,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  'user-round': UserRound,
  users: Users,
  wifi: Wifi,
  x: X,
};

export type NombreIcono = keyof typeof ICONOS | (string & {});

export function Icono({
  nombre,
  color = semantico.texto,
  tamano = campo.tamanoIcono,
}: {
  nombre: NombreIcono;
  color?: string;
  tamano?: number;
}) {
  const Componente = ICONOS[nombre] ?? Square;
  return <Componente color={color} size={tamano} strokeWidth={2} />;
}
